### ISSUE TITLE
Advancement error in latest.log

### ISSUE THREAD

**Issue by vico93** [SergoFox123/VerseCraft#3]
Basically, i got an error related to vercecraft that seems like an advancement have a JSON error:

`[11:53:46] [main/ERROR]: Parsing error loading custom advancement vercecraft:recipes/building_blocks/chiseled_calcite_bricks: Failed to parse either. First: Not a tag id; Second: Failed to parse either. First: Not a json array: "vercecraft:calcite_brick_slab"; Second: Failed to get element vercecraft:calcite_brick_slab missed input: {"has_calcite_brick_slab":{"conditions":{"items":[{"items":"vercecraft:calcite_brick_slab"}]},"trigger":"minecraft:inventory_changed"}}`

VerseCraft-2.0.0-Fabric+1.21

**Comment by SergoFox123** [comment]
Hi, thanks for pointing out the bug!
Will be fixed soon!

**Comment by SergoFox123** [comment]
Fixed! 
Fix will come in the next update

**Comment by SergoFox123** [comment]
Is there still a bug in update 3.0?

**Comment by vico93** [comment]
> Is there still a bug in update 3.0?

didnt see on my logs yet.
