### ISSUE TITLE
[Suggestion] Azalea Wood Set support

### ISSUE THREAD

**Issue by vico93** [SergoFox123/VerseCraft#4]
**Explain your suggestion here.**
Basically, add tiled variants of Azalea planks if [Azalea Wood Set](https://github.com/Fire-Horse27/azalea-wood) ([MR](https://modrinth.com/mod/azalea-wood-set)) is detected.

**Comment by SergoFox123** [comment]
Hi, I'll think about this proposal so I'm not closing this ticket for now.

**Comment by SergoFox123** [comment]
Plans have changed, azalea set blocks will be added in the next update. :)

**Comment by SergoFox123** [comment]
I'm closing this ticket since I released this.
Thanks for your feedback!

**Comment by vico93** [comment]
Just one question @SergoFox123 about the description of the release:

"Replaced a regular oak log with an azalea log." What do you mean? Did you removed oak-based blocks to place azalea in place?

**Comment by SergoFox123** [comment]
Yes

**Comment by vico93** [comment]
Oh that's bad. I thought you would just add azalea as an extension for the mod, not replacing a vanilla woodset-based to it!

**Comment by SergoFox123** [comment]
Nope, i added them separately

**Comment by SergoFox123** [comment]
I meant that in the vanilla azalea tree itself I replaced the oak trunk with an azalea trunk

**Comment by SergoFox123** [comment]
> > Я имел в виду, что в самом дереве ванильной азалии я заменил ствол дуба на ствол азалии.
> 
> о, в этом нет необходимости, так как мод азалии сам это делает

Well, I already did it. 
You can see the changes in the game :)

**Comment by vico93** [comment]
ahhh now i understand!

You've added a whole azalea wood set to the mod!

Actually i've requested initially just mosaics for the planks of the azalea mod ([this](https://modrinth.com/mod/azalea-wood-set)), but since you've added the whole set yourself, i will decide what mod i will use (the other woodset have a more darkish textures, while yours are nice too but more whitish).

**Comment by SergoFox123** [comment]
> аааа, теперь я понял!
> 
> Вы добавили в мод целый набор древесины азалии!
> 
> На самом деле, изначально я запросил только мозаику для досок мода азалии ( [это](https://modrinth.com/mod/azalea-wood-set) ), но поскольку вы добавили весь набор самостоятельно, я решу, какой мод я буду использовать (другой набор древесины имеет более темные текстуры, а ваш тоже хороши, но более беловатые).

oppps i thought you wanted me to add a whole set

**Comment by SergoFox123** [comment]
I thought you posted that mod as an example of the kit I should have made.

**Comment by vico93** [comment]
> > аааа, теперь я понял!
> > Вы добавили в мод целый набор древесины азалии!
> > На самом деле, изначально я запросил только мозаику для досок мода азалии ( [это](https://modrinth.com/mod/azalea-wood-set) ), но поскольку вы добавили весь набор самостоятельно, я решу, какой мод я буду использовать (другой набор древесины имеет более темные текстуры, а ваш тоже хороши, но более беловатые).
> 
> oppps i thought you wanted me to add a whole set

Your set is amazing, not gonna lie. Would totally use that. But the other set (texure-side) also is good.

Maybe a crazy idea, but to have the best of the two worlds, why not leave your set only for flowering azaleas, leaving the other for normal azaleas? Don't know if this is possible

**Comment by vico93** [comment]
If not possible i will stick with your mod, and see if i can use @Fire-Horse27's textures internally to override another wood set, either vanilla or something that WilderWild (other mod i use) adds.

**Comment by vico93** [comment]
Don't worry my friend! I will stick with your version of this wood set because i was looking for a whiter planks!

**Comment by vico93** [comment]
Now that the mod have a brand new wood set added, what about making the azalea wood set to have the same sounds of cherry ones? Looks similar in some aspects

**Comment by SergoFox123** [comment]
> Теперь, когда в мод добавлен совершенно новый набор дерева, как насчет того, чтобы набор дерева азалии издавал такие же звуки, как и вишневый? В некоторых аспектах похоже

I think I'll do it later :)
I need to take some time off after this release. Because there are still a few things I'm working on behind the scenes.

**Comment by SergoFox123** [comment]
> Теперь, когда в мод добавлен совершенно новый набор древесины, как насчет того, чтобы сделать набор древесины азалии с теми же звуками, что и у вишневых? В некоторых аспектах выглядит похоже

I did it in the hotfix 3.1.1
